version: "2"
services:
  app:
    container_name: app
    build: .
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    networks:
      - max-network
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/mongodb
    ports:
      - "27017:27017"
    networks:
      - max-network
  mysql:
    container_name: mysql
    image: mysql
    volumes:
      - ./data:/data/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: maxmilhas
    networks:
    - max-network
networks:
    max-network:
        driver: bridge